//
// スライダーコントロールの各種パラメータを設定する
//
function SliderControl_config()
{

// ☆ここから…

//;sliderControlImage = "config_slider_base2.png";	// スライダーコントロール（土台部分）の画像ファイル名
;tabImage = "config_slider_pin.png";				// ツマミの画像ファイル名
//;tabOffsetY = 0;								// スライダーコントロール上におけるツマミのＹ座標（ピクセル）
//;tabLeftMin = 0;								// 同、ツマミの可動範囲下限Ｘ座標（ピクセル）
//;tabLeftMax = 536;								// 同、ツマミの可動範囲上限Ｘ座標（ピクセル）

//;valueOffsetX = 550;							// 現在値表示用レイヤのＸ座標オフセット（ピクセル）
//;valueOffsetY = 6;								// 同、Ｙ座標オフセット（ピクセル）
;valueFormat = "%4d%s";							// 書式（４桁右寄せ＋単位）
;valueFontFace = "ＭＳ ゴシック";				// フォント名（等幅フォントであること）
;valueFontHeight = 16;							// フォントサイズ（ピクセル）
;valueFontBold = true;							// 太字にする場合はtrue
;valueFontColor = 0xffffff;						// 文字の色（0xRRGGBB形式/色定数）
;valueShadowLevel = 512;						// 影の不透明度（0:影なし）
;valueShadowColor = 0x000000;					// 影の色（0xRRGGBB形式/色定数）
;valueShadowWidth = 1;							// 影の幅（0:シャープ～ぼける）
;valueShadowOffsetX = 0;						// 影の位置のＸ座標（0:真下）
;valueShadowOffsetY = 0;						// 同、Ｙ座標（0:真下）

// ☆ここまでの間のパラメータを修正してください

}
