;macro_page_bt.ks

;‚¢‚¢‰ÁŒ¸ƒy[ƒWƒ{ƒ^ƒ“‚àƒ}ƒNƒ‚©‚µ‚Ä‚¨‚­‚©B

;---------------------------------------
;          ƒy[ƒWƒ{ƒ^ƒ“ SAVE            
;---------------------------------------
;‚±‚ê‚Íd‘g‚İ‚ªˆá‚¤‚©‚ç‚¢‚¢‚â

;---------------------------------------
;          ƒy[ƒWƒ{ƒ^ƒ“ LOAD            
;---------------------------------------
;‚±‚ê‚Íd‘g‚İ‚ªˆá‚¤‚©‚ç‚¢‚¢‚â

;---------------------------------------
;          ƒRƒ“ƒtƒBƒO—p    
;---------------------------------------

;ƒƒCƒ“ƒLƒƒƒ‰—p
[macro name=chara_on]
	[locate   x=%x   y=%y]
	;target“¯‚¶‚¾‚©‚çƒ}ƒNƒ‚ÉŠÜ‚ß‚Ä‚à‚¢‚¢‚¯‚ÇA‚Ç‚±”ò‚ñ‚Å‚é‚©–Ú‹‚Å•ª‚©‚ç‚È‚¢‚é‚©‚ç•’Ê‚É‘‚­B
	[button graphic="cnf_chara" storage=%storage target=%target exp=%exp enterse="&sf.SE_enter_sys" entersebuf="&sf.SE_enter_buf" clicksebuf="&sf.SE_click_buf"]
	[image left=%x top=%y storage=%graphic layer=%layer page=fore visible=true clipleft="&sf.cnf_chara_clipleft" cliptop="&sf.cnf_chara_cliptop" clipwidth="&sf.cnf_chara_clipwidth" clipheight="&sf.cnf_chara_clipheight" opacity=255 enterse="&sf.SE_enter_sys" entersebuf="&sf.SE_enter_buf" clicksebuf="&sf.SE_click_buf"]
[endmacro]

[macro name=chara_off]
	[locate   x=%x   y=%y]
	[button graphic=%graphic storage=%storage target=%target exp=%exp enterse="&sf.SE_enter_sys" entersebuf="&sf.SE_enter_buf" clicksebuf="&sf.SE_click_buf"]
[endmacro]


[macro name=chara_on_chgimage]
	[locate   x=%x   y=%y]
	;target“¯‚¶‚¾‚©‚çƒ}ƒNƒ‚ÉŠÜ‚ß‚Ä‚à‚¢‚¢‚¯‚ÇA‚Ç‚±”ò‚ñ‚Å‚é‚©–Ú‹‚Å•ª‚©‚ç‚È‚¢‚é‚©‚ç•’Ê‚É‘‚­B
	[button_chgimage num=%num graphic="cnf_chara" storage=%storage target=%target exp=%exp enterse="&sf.SE_enter_sys" entersebuf="&sf.SE_enter_buf" clicksebuf="&sf.SE_click_buf"]
	[image left=%x top=%y storage=%graphic layer=%layer page=fore visible=true clipleft="&sf.cnf_chara_clipleft" cliptop="&sf.cnf_chara_cliptop" clipwidth="&sf.cnf_chara_clipwidth" clipheight="&sf.cnf_chara_clipheight" opacity=255]
[endmacro]

[macro name=chara_off_chgimage]
	[locate   x=%x   y=%y]
	[button_chgimage num=%num graphic=%graphic storage=%storage target=%target exp=%exp enterse="&sf.SE_enter_sys" entersebuf="&sf.SE_enter_buf" clicksebuf="&sf.SE_click_buf"]
[endmacro]

;ƒ‚ƒu—p@ƒ{ƒ^ƒ“ƒTƒCƒYˆá‚¤‚©‚ç
[macro name=mob_on]
	[locate   x=%x   y=%y]
	;target“¯‚¶‚¾‚©‚çƒ}ƒNƒ‚ÉŠÜ‚ß‚Ä‚à‚¢‚¢‚¯‚ÇA‚Ç‚±”ò‚ñ‚Å‚é‚©–Ú‹‚Å•ª‚©‚ç‚È‚¢‚é‚©‚ç•’Ê‚É‘‚­B
	[button graphic="cnf_chara_mob" storage=%storage target=%target exp=%exp enterse="&sf.SE_enter_sys" entersebuf="&sf.SE_enter_buf" clicksebuf="&sf.SE_click_buf"]
	[image left=%x top=%y storage=%graphic layer=%layer page=fore visible=true clipleft="&sf.cnf_mob_clipleft" cliptop="&sf.cnf_mob_cliptop" clipwidth="&sf.cnf_mob_clipwidth" clipheight="&sf.cnf_mob_clipheight" opacity=255]
[endmacro]

[macro name=mob_off]
	[locate   x=%x   y=%y]
	[button graphic=%graphic storage=%storage target=%target exp=%exp enterse="&sf.SE_enter_sys" entersebuf="&sf.SE_enter_buf" clicksebuf="&sf.SE_click_buf"]
[endmacro]


[macro name=mob_on_chgimage]
	[locate   x=%x   y=%y]
	;target“¯‚¶‚¾‚©‚çƒ}ƒNƒ‚ÉŠÜ‚ß‚Ä‚à‚¢‚¢‚¯‚ÇA‚Ç‚±”ò‚ñ‚Å‚é‚©–Ú‹‚Å•ª‚©‚ç‚È‚¢‚é‚©‚ç•’Ê‚É‘‚­B
	[button_chgimage num=%num graphic="cnf_chara_mob" storage=%storage target=%target exp=%exp enterse="&sf.SE_enter_sys" entersebuf="&sf.SE_enter_buf" clicksebuf="&sf.SE_click_buf"]
	[image left=%x top=%y storage=%graphic layer=%layer page=fore visible=true clipleft="&sf.cnf_mob_clipleft" cliptop="&sf.cnf_mob_cliptop" clipwidth="&sf.cnf_mob_clipwidth" clipheight="&sf.cnf_mob_clipheight" opacity=255]
[endmacro]

[macro name=mob_off_chgimage]
	[locate   x=%x   y=%y]
	[button_chgimage num=%num graphic=%graphic storage=%storage target=%target exp=%exp enterse="&sf.SE_enter_sys" entersebuf="&sf.SE_enter_buf" clicksebuf="&sf.SE_click_buf"]
[endmacro]
;---------------------------------------
;          ƒy[ƒWƒ{ƒ^ƒ“ CG SCENEŒ“—p    
;---------------------------------------

[macro name=pagebt_now]
	[locate   x=%x   y=%y]
	;target“¯‚¶‚¾‚©‚çƒ}ƒNƒ‚ÉŠÜ‚ß‚Ä‚à‚¢‚¢‚¯‚ÇA‚Ç‚±”ò‚ñ‚Å‚é‚©–Ú‹‚Å•ª‚©‚ç‚È‚¢‚é‚©‚ç•’Ê‚É‘‚­B
;SE	[button graphic="b_page" target=%target exp=%exp enterse="&sf.SE_enter_sys"  entersebuf="&sf.SE_enter_buf" clicksebuf="&sf.SE_click_buf"]
	[button graphic="b_page" target=%target exp=%exp]
	[image left=%x top=%y storage=%graphic layer="&sf.layer_b_page" page=fore visible=true clipleft="&sf.b_page_clipleft" cliptop="&sf.b_page_cliptop" clipwidth="&sf.b_page_clipwidth" clipheight="&sf.b_page_clipheight" opacity=255]
[endmacro]

[macro name=pagebt]
	[locate   x=%x   y=%y]
	[button graphic=%graphic target=%target exp=%exp]
[endmacro]

;---------------------------------------
;          ƒy[ƒWƒ{ƒ^ƒ“ CG              
;---------------------------------------
;ƒTƒuƒ‹[ƒ`ƒ“‚Æƒ}ƒNƒ‚Ç‚Á‚¿‚ª‚¢‚¢‚ñ‚¶‚á‚ëH
[macro name=pagebt_CG]

	; ƒy[ƒWƒ{ƒ^ƒ“•\¦
	;1ƒy[ƒW‚¾‚¯‚È‚çİ’èƒtƒ@ƒCƒ‹‚¾‚¯“Ç‚İ‚É‚¢‚­
	[if    exp="sf.CG_page == 1  && sf.CG_page_max == 1"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è01]
	[elsif exp="sf.CG_page == 1  && sf.CG_page_max >= 1"]
		;—§‚¿
	;‚â‚Á‚Ï‚â‚ß	[image storage="bg_title_chara_OBA1_3" layer=0 page=fore visible=true left=450 top=0 opacity=255]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è01]
		[pagebt_now x="&tf.b_cg_pageX[1]"  y="&tf.b_cg_pageY[1]"  graphic="b_page01" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 1"  cond="sf.CG_page_max >= 1"]
		[pagebt     x="&tf.b_cg_pageX[2]"  y="&tf.b_cg_pageY[2]"  graphic="b_page02" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 2"  cond="sf.CG_page_max >= 2"]
		[pagebt     x="&tf.b_cg_pageX[3]"  y="&tf.b_cg_pageY[3]"  graphic="b_page03" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 3"  cond="sf.CG_page_max >= 3"]
		[pagebt     x="&tf.b_cg_pageX[4]"  y="&tf.b_cg_pageY[4]"  graphic="b_page04" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 4"  cond="sf.CG_page_max >= 4"]
		[pagebt     x="&tf.b_cg_pageX[5]"  y="&tf.b_cg_pageY[5]"  graphic="b_page05" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 5"  cond="sf.CG_page_max >= 5"]
		[pagebt     x="&tf.b_cg_pageX[6]"  y="&tf.b_cg_pageY[6]"  graphic="b_page06" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 6"  cond="sf.CG_page_max >= 6"]
		[pagebt     x="&tf.b_cg_pageX[7]"  y="&tf.b_cg_pageY[7]"  graphic="b_page07" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 7"  cond="sf.CG_page_max >= 7"]
		[pagebt     x="&tf.b_cg_pageX[8]"  y="&tf.b_cg_pageY[8]"  graphic="b_page08" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 8"  cond="sf.CG_page_max >= 8"]
		[pagebt     x="&tf.b_cg_pageX[9]"  y="&tf.b_cg_pageY[9]"  graphic="b_page09" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 9"  cond="sf.CG_page_max >= 9"]
		[pagebt     x="&tf.b_cg_pageX[10]" y="&tf.b_cg_pageY[10]" graphic="b_page10" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 10" cond="sf.CG_page_max >= 10"]
	[elsif exp="sf.CG_page == 2  && sf.CG_page_max >= 2"]
		;—§‚¿
	;‚â‚Á‚Ï‚â‚ß	[image storage="bg_title_chara_OBA2_1" layer=0 page=fore visible=true left=480 top=0 opacity=255]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è02]
		[pagebt     x="&tf.b_cg_pageX[1]"  y="&tf.b_cg_pageY[1]"  graphic="b_page01" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 1"  cond="sf.CG_page_max >= 1"]
		[pagebt_now x="&tf.b_cg_pageX[2]"  y="&tf.b_cg_pageY[2]"  graphic="b_page02" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 2"  cond="sf.CG_page_max >= 2"]
		[pagebt     x="&tf.b_cg_pageX[3]"  y="&tf.b_cg_pageY[3]"  graphic="b_page03" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 3"  cond="sf.CG_page_max >= 3"]
		[pagebt     x="&tf.b_cg_pageX[4]"  y="&tf.b_cg_pageY[4]"  graphic="b_page04" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 4"  cond="sf.CG_page_max >= 4"]
		[pagebt     x="&tf.b_cg_pageX[5]"  y="&tf.b_cg_pageY[5]"  graphic="b_page05" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 5"  cond="sf.CG_page_max >= 5"]
		[pagebt     x="&tf.b_cg_pageX[6]"  y="&tf.b_cg_pageY[6]"  graphic="b_page06" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 6"  cond="sf.CG_page_max >= 6"]
		[pagebt     x="&tf.b_cg_pageX[7]"  y="&tf.b_cg_pageY[7]"  graphic="b_page07" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 7"  cond="sf.CG_page_max >= 7"]
		[pagebt     x="&tf.b_cg_pageX[8]"  y="&tf.b_cg_pageY[8]"  graphic="b_page08" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 8"  cond="sf.CG_page_max >= 8"]
		[pagebt     x="&tf.b_cg_pageX[9]"  y="&tf.b_cg_pageY[9]"  graphic="b_page09" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 9"  cond="sf.CG_page_max >= 9"]
		[pagebt     x="&tf.b_cg_pageX[10]" y="&tf.b_cg_pageY[10]" graphic="b_page10" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 10" cond="sf.CG_page_max >= 10"]
	[elsif exp="sf.CG_page == 3  && sf.CG_page_max >= 3"]
		;—§‚¿
	;‚â‚Á‚Ï‚â‚ß	[image storage="bg_title_chara_TLE1_3" layer=0 page=fore visible=true left=450 top=0 opacity=255]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è03]
		[pagebt     x="&tf.b_cg_pageX[1]"  y="&tf.b_cg_pageY[1]"  graphic="b_page01" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 1"  cond="sf.CG_page_max >= 1"]
		[pagebt     x="&tf.b_cg_pageX[2]"  y="&tf.b_cg_pageY[2]"  graphic="b_page02" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 2"  cond="sf.CG_page_max >= 2"]
		[pagebt_now x="&tf.b_cg_pageX[3]"  y="&tf.b_cg_pageY[3]"  graphic="b_page03" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 3"  cond="sf.CG_page_max >= 3"]
		[pagebt     x="&tf.b_cg_pageX[4]"  y="&tf.b_cg_pageY[4]"  graphic="b_page04" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 4"  cond="sf.CG_page_max >= 4"]
		[pagebt     x="&tf.b_cg_pageX[5]"  y="&tf.b_cg_pageY[5]"  graphic="b_page05" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 5"  cond="sf.CG_page_max >= 5"]
		[pagebt     x="&tf.b_cg_pageX[6]"  y="&tf.b_cg_pageY[6]"  graphic="b_page06" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 6"  cond="sf.CG_page_max >= 6"]
		[pagebt     x="&tf.b_cg_pageX[7]"  y="&tf.b_cg_pageY[7]"  graphic="b_page07" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 7"  cond="sf.CG_page_max >= 7"]
		[pagebt     x="&tf.b_cg_pageX[8]"  y="&tf.b_cg_pageY[8]"  graphic="b_page08" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 8"  cond="sf.CG_page_max >= 8"]
		[pagebt     x="&tf.b_cg_pageX[9]"  y="&tf.b_cg_pageY[9]"  graphic="b_page09" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 9"  cond="sf.CG_page_max >= 9"]
		[pagebt     x="&tf.b_cg_pageX[10]" y="&tf.b_cg_pageY[10]" graphic="b_page10" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 10" cond="sf.CG_page_max >= 10"]
	[elsif exp="sf.CG_page == 4  && sf.CG_page_max >= 4"]
		;—§‚¿
	;‚â‚Á‚Ï‚â‚ß	[image storage="bg_title_chara_TLE4_1" layer=0 page=fore visible=true left=420 top=0 opacity=255]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è04]
		[pagebt     x="&tf.b_cg_pageX[1]"  y="&tf.b_cg_pageY[1]"  graphic="b_page01" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 1"  cond="sf.CG_page_max >= 1"]
		[pagebt     x="&tf.b_cg_pageX[2]"  y="&tf.b_cg_pageY[2]"  graphic="b_page02" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 2"  cond="sf.CG_page_max >= 2"]
		[pagebt     x="&tf.b_cg_pageX[3]"  y="&tf.b_cg_pageY[3]"  graphic="b_page03" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 3"  cond="sf.CG_page_max >= 3"]
		[pagebt_now x="&tf.b_cg_pageX[4]"  y="&tf.b_cg_pageY[4]"  graphic="b_page04" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 4"  cond="sf.CG_page_max >= 4"]
		[pagebt     x="&tf.b_cg_pageX[5]"  y="&tf.b_cg_pageY[5]"  graphic="b_page05" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 5"  cond="sf.CG_page_max >= 5"]
		[pagebt     x="&tf.b_cg_pageX[6]"  y="&tf.b_cg_pageY[6]"  graphic="b_page06" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 6"  cond="sf.CG_page_max >= 6"]
		[pagebt     x="&tf.b_cg_pageX[7]"  y="&tf.b_cg_pageY[7]"  graphic="b_page07" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 7"  cond="sf.CG_page_max >= 7"]
		[pagebt     x="&tf.b_cg_pageX[8]"  y="&tf.b_cg_pageY[8]"  graphic="b_page08" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 8"  cond="sf.CG_page_max >= 8"]
		[pagebt     x="&tf.b_cg_pageX[9]"  y="&tf.b_cg_pageY[9]"  graphic="b_page09" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 9"  cond="sf.CG_page_max >= 9"]
		[pagebt     x="&tf.b_cg_pageX[10]" y="&tf.b_cg_pageY[10]" graphic="b_page10" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 10" cond="sf.CG_page_max >= 10"]
	[elsif exp="sf.CG_page == 5  && sf.CG_page_max >= 5"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è05]
		[pagebt     x="&tf.b_cg_pageX[1]"  y="&tf.b_cg_pageY[1]"  graphic="b_page01" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 1"  cond="sf.CG_page_max >= 1"]
		[pagebt     x="&tf.b_cg_pageX[2]"  y="&tf.b_cg_pageY[2]"  graphic="b_page02" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 2"  cond="sf.CG_page_max >= 2"]
		[pagebt     x="&tf.b_cg_pageX[3]"  y="&tf.b_cg_pageY[3]"  graphic="b_page03" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 3"  cond="sf.CG_page_max >= 3"]
		[pagebt     x="&tf.b_cg_pageX[4]"  y="&tf.b_cg_pageY[4]"  graphic="b_page04" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 4"  cond="sf.CG_page_max >= 4"]
		[pagebt_now x="&tf.b_cg_pageX[5]"  y="&tf.b_cg_pageY[5]"  graphic="b_page05" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 5"  cond="sf.CG_page_max >= 5"]
		[pagebt     x="&tf.b_cg_pageX[6]"  y="&tf.b_cg_pageY[6]"  graphic="b_page06" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 6"  cond="sf.CG_page_max >= 6"]
		[pagebt     x="&tf.b_cg_pageX[7]"  y="&tf.b_cg_pageY[7]"  graphic="b_page07" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 7"  cond="sf.CG_page_max >= 7"]
		[pagebt     x="&tf.b_cg_pageX[8]"  y="&tf.b_cg_pageY[8]"  graphic="b_page08" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 8"  cond="sf.CG_page_max >= 8"]
		[pagebt     x="&tf.b_cg_pageX[9]"  y="&tf.b_cg_pageY[9]"  graphic="b_page09" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 9"  cond="sf.CG_page_max >= 9"]
		[pagebt     x="&tf.b_cg_pageX[10]" y="&tf.b_cg_pageY[10]" graphic="b_page10" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 10" cond="sf.CG_page_max >= 10"]
	[elsif exp="sf.CG_page == 6  && sf.CG_page_max >= 6"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è06]
		[pagebt     x="&tf.b_cg_pageX[1]"  y="&tf.b_cg_pageY[1]"  graphic="b_page01" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 1"  cond="sf.CG_page_max >= 1"]
		[pagebt     x="&tf.b_cg_pageX[2]"  y="&tf.b_cg_pageY[2]"  graphic="b_page02" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 2"  cond="sf.CG_page_max >= 2"]
		[pagebt     x="&tf.b_cg_pageX[3]"  y="&tf.b_cg_pageY[3]"  graphic="b_page03" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 3"  cond="sf.CG_page_max >= 3"]
		[pagebt     x="&tf.b_cg_pageX[4]"  y="&tf.b_cg_pageY[4]"  graphic="b_page04" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 4"  cond="sf.CG_page_max >= 4"]
		[pagebt     x="&tf.b_cg_pageX[5]"  y="&tf.b_cg_pageY[5]"  graphic="b_page05" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 5"  cond="sf.CG_page_max >= 5"]
		[pagebt_now x="&tf.b_cg_pageX[6]"  y="&tf.b_cg_pageY[6]"  graphic="b_page06" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 6"  cond="sf.CG_page_max >= 6"]
		[pagebt     x="&tf.b_cg_pageX[7]"  y="&tf.b_cg_pageY[7]"  graphic="b_page07" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 7"  cond="sf.CG_page_max >= 7"]
		[pagebt     x="&tf.b_cg_pageX[8]"  y="&tf.b_cg_pageY[8]"  graphic="b_page08" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 8"  cond="sf.CG_page_max >= 8"]
		[pagebt     x="&tf.b_cg_pageX[9]"  y="&tf.b_cg_pageY[9]"  graphic="b_page09" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 9"  cond="sf.CG_page_max >= 9"]
		[pagebt     x="&tf.b_cg_pageX[10]" y="&tf.b_cg_pageY[10]" graphic="b_page10" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 10" cond="sf.CG_page_max >= 10"]
	[elsif exp="sf.CG_page == 7  && sf.CG_page_max >= 7"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è07]
		[pagebt     x="&tf.b_cg_pageX[1]"  y="&tf.b_cg_pageY[1]"  graphic="b_page01" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 1"  cond="sf.CG_page_max >= 1"]
		[pagebt     x="&tf.b_cg_pageX[2]"  y="&tf.b_cg_pageY[2]"  graphic="b_page02" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 2"  cond="sf.CG_page_max >= 2"]
		[pagebt     x="&tf.b_cg_pageX[3]"  y="&tf.b_cg_pageY[3]"  graphic="b_page03" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 3"  cond="sf.CG_page_max >= 3"]
		[pagebt     x="&tf.b_cg_pageX[4]"  y="&tf.b_cg_pageY[4]"  graphic="b_page04" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 4"  cond="sf.CG_page_max >= 4"]
		[pagebt     x="&tf.b_cg_pageX[5]"  y="&tf.b_cg_pageY[5]"  graphic="b_page05" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 5"  cond="sf.CG_page_max >= 5"]
		[pagebt     x="&tf.b_cg_pageX[6]"  y="&tf.b_cg_pageY[6]"  graphic="b_page06" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 6"  cond="sf.CG_page_max >= 6"]
		[pagebt_now x="&tf.b_cg_pageX[7]"  y="&tf.b_cg_pageY[7]"  graphic="b_page07" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 7"  cond="sf.CG_page_max >= 7"]
		[pagebt     x="&tf.b_cg_pageX[8]"  y="&tf.b_cg_pageY[8]"  graphic="b_page08" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 8"  cond="sf.CG_page_max >= 8"]
		[pagebt     x="&tf.b_cg_pageX[9]"  y="&tf.b_cg_pageY[9]"  graphic="b_page09" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 9"  cond="sf.CG_page_max >= 9"]
		[pagebt     x="&tf.b_cg_pageX[10]" y="&tf.b_cg_pageY[10]" graphic="b_page10" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 10" cond="sf.CG_page_max >= 10"]
	[elsif exp="sf.CG_page == 8  && sf.CG_page_max >= 8"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è08]
		[pagebt     x="&tf.b_cg_pageX[1]"  y="&tf.b_cg_pageY[1]"  graphic="b_page01" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 1"  cond="sf.CG_page_max >= 1"]
		[pagebt     x="&tf.b_cg_pageX[2]"  y="&tf.b_cg_pageY[2]"  graphic="b_page02" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 2"  cond="sf.CG_page_max >= 2"]
		[pagebt     x="&tf.b_cg_pageX[3]"  y="&tf.b_cg_pageY[3]"  graphic="b_page03" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 3"  cond="sf.CG_page_max >= 3"]
		[pagebt     x="&tf.b_cg_pageX[4]"  y="&tf.b_cg_pageY[4]"  graphic="b_page04" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 4"  cond="sf.CG_page_max >= 4"]
		[pagebt     x="&tf.b_cg_pageX[5]"  y="&tf.b_cg_pageY[5]"  graphic="b_page05" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 5"  cond="sf.CG_page_max >= 5"]
		[pagebt     x="&tf.b_cg_pageX[6]"  y="&tf.b_cg_pageY[6]"  graphic="b_page06" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 6"  cond="sf.CG_page_max >= 6"]
		[pagebt     x="&tf.b_cg_pageX[7]"  y="&tf.b_cg_pageY[7]"  graphic="b_page07" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 7"  cond="sf.CG_page_max >= 7"]
		[pagebt_now x="&tf.b_cg_pageX[8]"  y="&tf.b_cg_pageY[8]"  graphic="b_page08" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 8"  cond="sf.CG_page_max >= 8"]
		[pagebt     x="&tf.b_cg_pageX[9]"  y="&tf.b_cg_pageY[9]"  graphic="b_page09" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 9"  cond="sf.CG_page_max >= 9"]
		[pagebt     x="&tf.b_cg_pageX[10]" y="&tf.b_cg_pageY[10]" graphic="b_page10" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 10" cond="sf.CG_page_max >= 10"]
	[elsif exp="sf.CG_page == 9  && sf.CG_page_max >= 9"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è09]
		[pagebt     x="&tf.b_cg_pageX[1]"  y="&tf.b_cg_pageY[1]"  graphic="b_page01" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 1"  cond="sf.CG_page_max >= 1"]
		[pagebt     x="&tf.b_cg_pageX[2]"  y="&tf.b_cg_pageY[2]"  graphic="b_page02" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 2"  cond="sf.CG_page_max >= 2"]
		[pagebt     x="&tf.b_cg_pageX[3]"  y="&tf.b_cg_pageY[3]"  graphic="b_page03" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 3"  cond="sf.CG_page_max >= 3"]
		[pagebt     x="&tf.b_cg_pageX[4]"  y="&tf.b_cg_pageY[4]"  graphic="b_page04" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 4"  cond="sf.CG_page_max >= 4"]
		[pagebt     x="&tf.b_cg_pageX[5]"  y="&tf.b_cg_pageY[5]"  graphic="b_page05" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 5"  cond="sf.CG_page_max >= 5"]
		[pagebt     x="&tf.b_cg_pageX[6]"  y="&tf.b_cg_pageY[6]"  graphic="b_page06" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 6"  cond="sf.CG_page_max >= 6"]
		[pagebt     x="&tf.b_cg_pageX[7]"  y="&tf.b_cg_pageY[7]"  graphic="b_page07" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 7"  cond="sf.CG_page_max >= 7"]
		[pagebt     x="&tf.b_cg_pageX[8]"  y="&tf.b_cg_pageY[8]"  graphic="b_page08" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 8"  cond="sf.CG_page_max >= 8"]
		[pagebt_now x="&tf.b_cg_pageX[9]"  y="&tf.b_cg_pageY[9]"  graphic="b_page09" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 9"  cond="sf.CG_page_max >= 9"]
		[pagebt     x="&tf.b_cg_pageX[10]" y="&tf.b_cg_pageY[10]" graphic="b_page10" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 10" cond="sf.CG_page_max >= 10"]
	[elsif exp="sf.CG_page == 10 && sf.CG_page_max >= 10"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_cgmode_init.ks'" target=*CG‚ÆƒTƒ€ƒlİ’è10]
		[pagebt     x="&tf.b_cg_pageX[1]"  y="&tf.b_cg_pageY[1]"  graphic="b_page01" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 1"  cond="sf.CG_page_max >= 1"]
		[pagebt     x="&tf.b_cg_pageX[2]"  y="&tf.b_cg_pageY[2]"  graphic="b_page02" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 2"  cond="sf.CG_page_max >= 2"]
		[pagebt     x="&tf.b_cg_pageX[3]"  y="&tf.b_cg_pageY[3]"  graphic="b_page03" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 3"  cond="sf.CG_page_max >= 3"]
		[pagebt     x="&tf.b_cg_pageX[4]"  y="&tf.b_cg_pageY[4]"  graphic="b_page04" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 4"  cond="sf.CG_page_max >= 4"]
		[pagebt     x="&tf.b_cg_pageX[5]"  y="&tf.b_cg_pageY[5]"  graphic="b_page05" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 5"  cond="sf.CG_page_max >= 5"]
		[pagebt     x="&tf.b_cg_pageX[6]"  y="&tf.b_cg_pageY[6]"  graphic="b_page06" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 6"  cond="sf.CG_page_max >= 6"]
		[pagebt     x="&tf.b_cg_pageX[7]"  y="&tf.b_cg_pageY[7]"  graphic="b_page07" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 7"  cond="sf.CG_page_max >= 7"]
		[pagebt     x="&tf.b_cg_pageX[8]"  y="&tf.b_cg_pageY[8]"  graphic="b_page08" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 8"  cond="sf.CG_page_max >= 8"]
		[pagebt     x="&tf.b_cg_pageX[9]"  y="&tf.b_cg_pageY[9]"  graphic="b_page09" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 9"  cond="sf.CG_page_max >= 9"]
		[pagebt_now x="&tf.b_cg_pageX[10]" y="&tf.b_cg_pageY[10]" graphic="b_page10" target=*CGMODEÄ•`‰æ exp="sf.CG_page = 10" cond="sf.CG_page_max >= 10"]
	[endif]

[endmacro]

;---------------------------------------
;          ƒy[ƒWƒ{ƒ^ƒ“ SCENE           
;---------------------------------------
[macro name=pagebt_SR]

	; ƒy[ƒWƒ{ƒ^ƒ“•\¦
	;1ƒy[ƒW‚¾‚¯‚È‚çİ’èƒtƒ@ƒCƒ‹‚¾‚¯“Ç‚İ‚É‚¢‚­
	[if    exp="sf.SR_page == 1  && sf.SR_page_max == 1"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è01]
	[elsif exp="sf.SR_page == 1  && sf.SR_page_max >= 1"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è01]
		[pagebt_now x="&tf.b_sr_pageX[1]"  y="&tf.b_sr_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&tf.b_sr_pageX[2]"  y="&tf.b_sr_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&tf.b_sr_pageX[3]"  y="&tf.b_sr_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&tf.b_sr_pageX[4]"  y="&tf.b_sr_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&tf.b_sr_pageX[5]"  y="&tf.b_sr_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&tf.b_sr_pageX[6]"  y="&tf.b_sr_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&tf.b_sr_pageX[7]"  y="&tf.b_sr_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&tf.b_sr_pageX[8]"  y="&tf.b_sr_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&tf.b_sr_pageX[9]"  y="&tf.b_sr_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&tf.b_sr_pageX[10]" y="&tf.b_sr_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 2  && sf.SR_page_max >= 2"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è02]
		[pagebt     x="&tf.b_sr_pageX[1]"  y="&tf.b_sr_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt_now x="&tf.b_sr_pageX[2]"  y="&tf.b_sr_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&tf.b_sr_pageX[3]"  y="&tf.b_sr_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&tf.b_sr_pageX[4]"  y="&tf.b_sr_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&tf.b_sr_pageX[5]"  y="&tf.b_sr_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&tf.b_sr_pageX[6]"  y="&tf.b_sr_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&tf.b_sr_pageX[7]"  y="&tf.b_sr_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&tf.b_sr_pageX[8]"  y="&tf.b_sr_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&tf.b_sr_pageX[9]"  y="&tf.b_sr_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&tf.b_sr_pageX[10]" y="&tf.b_sr_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 3  && sf.SR_page_max >= 3"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è03]
		[pagebt     x="&tf.b_sr_pageX[1]"  y="&tf.b_sr_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&tf.b_sr_pageX[2]"  y="&tf.b_sr_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt_now x="&tf.b_sr_pageX[3]"  y="&tf.b_sr_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&tf.b_sr_pageX[4]"  y="&tf.b_sr_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&tf.b_sr_pageX[5]"  y="&tf.b_sr_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&tf.b_sr_pageX[6]"  y="&tf.b_sr_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&tf.b_sr_pageX[7]"  y="&tf.b_sr_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&tf.b_sr_pageX[8]"  y="&tf.b_sr_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&tf.b_sr_pageX[9]"  y="&tf.b_sr_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&tf.b_sr_pageX[10]" y="&tf.b_sr_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 4  && sf.SR_page_max >= 4"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è04]
		[pagebt     x="&tf.b_sr_pageX[1]"  y="&tf.b_sr_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&tf.b_sr_pageX[2]"  y="&tf.b_sr_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&tf.b_sr_pageX[3]"  y="&tf.b_sr_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt_now x="&tf.b_sr_pageX[4]"  y="&tf.b_sr_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&tf.b_sr_pageX[5]"  y="&tf.b_sr_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&tf.b_sr_pageX[6]"  y="&tf.b_sr_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&tf.b_sr_pageX[7]"  y="&tf.b_sr_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&tf.b_sr_pageX[8]"  y="&tf.b_sr_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&tf.b_sr_pageX[9]"  y="&tf.b_sr_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&tf.b_sr_pageX[10]" y="&tf.b_sr_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 5  && sf.SR_page_max >= 5"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è05]
		[pagebt     x="&tf.b_sr_pageX[1]"  y="&tf.b_sr_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&tf.b_sr_pageX[2]"  y="&tf.b_sr_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&tf.b_sr_pageX[3]"  y="&tf.b_sr_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&tf.b_sr_pageX[4]"  y="&tf.b_sr_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt_now x="&tf.b_sr_pageX[5]"  y="&tf.b_sr_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&tf.b_sr_pageX[6]"  y="&tf.b_sr_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&tf.b_sr_pageX[7]"  y="&tf.b_sr_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&tf.b_sr_pageX[8]"  y="&tf.b_sr_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&tf.b_sr_pageX[9]"  y="&tf.b_sr_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&tf.b_sr_pageX[10]" y="&tf.b_sr_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 6  && sf.SR_page_max >= 6"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è06]
		[pagebt     x="&tf.b_sr_pageX[1]"  y="&tf.b_sr_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&tf.b_sr_pageX[2]"  y="&tf.b_sr_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&tf.b_sr_pageX[3]"  y="&tf.b_sr_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&tf.b_sr_pageX[4]"  y="&tf.b_sr_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&tf.b_sr_pageX[5]"  y="&tf.b_sr_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt_now x="&tf.b_sr_pageX[6]"  y="&tf.b_sr_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&tf.b_sr_pageX[7]"  y="&tf.b_sr_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&tf.b_sr_pageX[8]"  y="&tf.b_sr_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&tf.b_sr_pageX[9]"  y="&tf.b_sr_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&tf.b_sr_pageX[10]" y="&tf.b_sr_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 7  && sf.SR_page_max >= 7"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è07]
		[pagebt     x="&tf.b_sr_pageX[1]"  y="&tf.b_sr_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&tf.b_sr_pageX[2]"  y="&tf.b_sr_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&tf.b_sr_pageX[3]"  y="&tf.b_sr_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&tf.b_sr_pageX[4]"  y="&tf.b_sr_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&tf.b_sr_pageX[5]"  y="&tf.b_sr_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&tf.b_sr_pageX[6]"  y="&tf.b_sr_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt_now x="&tf.b_sr_pageX[7]"  y="&tf.b_sr_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&tf.b_sr_pageX[8]"  y="&tf.b_sr_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&tf.b_sr_pageX[9]"  y="&tf.b_sr_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&tf.b_sr_pageX[10]" y="&tf.b_sr_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 8  && sf.SR_page_max >= 8"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è08]
		[pagebt     x="&tf.b_sr_pageX[1]"  y="&tf.b_sr_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&tf.b_sr_pageX[2]"  y="&tf.b_sr_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&tf.b_sr_pageX[3]"  y="&tf.b_sr_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&tf.b_sr_pageX[4]"  y="&tf.b_sr_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&tf.b_sr_pageX[5]"  y="&tf.b_sr_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&tf.b_sr_pageX[6]"  y="&tf.b_sr_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&tf.b_sr_pageX[7]"  y="&tf.b_sr_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt_now x="&tf.b_sr_pageX[8]"  y="&tf.b_sr_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&tf.b_sr_pageX[9]"  y="&tf.b_sr_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&tf.b_sr_pageX[10]" y="&tf.b_sr_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 9  && sf.SR_page_max >= 9"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è09]
		[pagebt     x="&tf.b_sr_pageX[1]"  y="&tf.b_sr_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&tf.b_sr_pageX[2]"  y="&tf.b_sr_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&tf.b_sr_pageX[3]"  y="&tf.b_sr_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&tf.b_sr_pageX[4]"  y="&tf.b_sr_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&tf.b_sr_pageX[5]"  y="&tf.b_sr_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&tf.b_sr_pageX[6]"  y="&tf.b_sr_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&tf.b_sr_pageX[7]"  y="&tf.b_sr_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&tf.b_sr_pageX[8]"  y="&tf.b_sr_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt_now x="&tf.b_sr_pageX[9]"  y="&tf.b_sr_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&tf.b_sr_pageX[10]" y="&tf.b_sr_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 10 && sf.SR_page_max >= 10"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="&sf.addgameID + 'b_scene_init.ks'" target=*SR‚ÆƒTƒ€ƒlİ’è10]
		[pagebt     x="&tf.b_sr_pageX[1]"  y="&tf.b_sr_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&tf.b_sr_pageX[2]"  y="&tf.b_sr_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&tf.b_sr_pageX[3]"  y="&tf.b_sr_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&tf.b_sr_pageX[4]"  y="&tf.b_sr_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&tf.b_sr_pageX[5]"  y="&tf.b_sr_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&tf.b_sr_pageX[6]"  y="&tf.b_sr_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&tf.b_sr_pageX[7]"  y="&tf.b_sr_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&tf.b_sr_pageX[8]"  y="&tf.b_sr_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&tf.b_sr_pageX[9]"  y="&tf.b_sr_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt_now x="&tf.b_sr_pageX[10]" y="&tf.b_sr_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[endif]

[endmacro]


;---------------------------------------
;          ƒy[ƒWƒ{ƒ^ƒ“ SCENEViewer     
;---------------------------------------
[macro name=pagebt_SV]

	; ƒy[ƒWƒ{ƒ^ƒ“•\¦
	;1ƒy[ƒW‚¾‚¯‚È‚çİ’èƒtƒ@ƒCƒ‹‚¾‚¯“Ç‚İ‚É‚¢‚­
	[if    exp="sf.SR_page == 1  && sf.SR_page_max == 1"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è01]
	[elsif exp="sf.SR_page == 1  && sf.SR_page_max >= 1"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è01]
		[pagebt_now x="&sf.b_sv_pageX[1]"  y="&sf.b_sv_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&sf.b_sv_pageX[2]"  y="&sf.b_sv_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&sf.b_sv_pageX[3]"  y="&sf.b_sv_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&sf.b_sv_pageX[4]"  y="&sf.b_sv_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&sf.b_sv_pageX[5]"  y="&sf.b_sv_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&sf.b_sv_pageX[6]"  y="&sf.b_sv_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&sf.b_sv_pageX[7]"  y="&sf.b_sv_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&sf.b_sv_pageX[8]"  y="&sf.b_sv_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&sf.b_sv_pageX[9]"  y="&sf.b_sv_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&sf.b_sv_pageX[10]" y="&sf.b_sv_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 2  && sf.SR_page_max >= 2"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è02]
		[pagebt     x="&sf.b_sv_pageX[1]"  y="&sf.b_sv_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt_now x="&sf.b_sv_pageX[2]"  y="&sf.b_sv_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&sf.b_sv_pageX[3]"  y="&sf.b_sv_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&sf.b_sv_pageX[4]"  y="&sf.b_sv_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&sf.b_sv_pageX[5]"  y="&sf.b_sv_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&sf.b_sv_pageX[6]"  y="&sf.b_sv_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&sf.b_sv_pageX[7]"  y="&sf.b_sv_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&sf.b_sv_pageX[8]"  y="&sf.b_sv_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&sf.b_sv_pageX[9]"  y="&sf.b_sv_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&sf.b_sv_pageX[10]" y="&sf.b_sv_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 3  && sf.SR_page_max >= 3"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è03]
		[pagebt     x="&sf.b_sv_pageX[1]"  y="&sf.b_sv_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&sf.b_sv_pageX[2]"  y="&sf.b_sv_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt_now x="&sf.b_sv_pageX[3]"  y="&sf.b_sv_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&sf.b_sv_pageX[4]"  y="&sf.b_sv_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&sf.b_sv_pageX[5]"  y="&sf.b_sv_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&sf.b_sv_pageX[6]"  y="&sf.b_sv_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&sf.b_sv_pageX[7]"  y="&sf.b_sv_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&sf.b_sv_pageX[8]"  y="&sf.b_sv_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&sf.b_sv_pageX[9]"  y="&sf.b_sv_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&sf.b_sv_pageX[10]" y="&sf.b_sv_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 4  && sf.SR_page_max >= 4"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è04]
		[pagebt     x="&sf.b_sv_pageX[1]"  y="&sf.b_sv_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&sf.b_sv_pageX[2]"  y="&sf.b_sv_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&sf.b_sv_pageX[3]"  y="&sf.b_sv_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt_now x="&sf.b_sv_pageX[4]"  y="&sf.b_sv_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&sf.b_sv_pageX[5]"  y="&sf.b_sv_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&sf.b_sv_pageX[6]"  y="&sf.b_sv_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&sf.b_sv_pageX[7]"  y="&sf.b_sv_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&sf.b_sv_pageX[8]"  y="&sf.b_sv_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&sf.b_sv_pageX[9]"  y="&sf.b_sv_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&sf.b_sv_pageX[10]" y="&sf.b_sv_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 5  && sf.SR_page_max >= 5"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è05]
		[pagebt     x="&sf.b_sv_pageX[1]"  y="&sf.b_sv_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&sf.b_sv_pageX[2]"  y="&sf.b_sv_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&sf.b_sv_pageX[3]"  y="&sf.b_sv_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&sf.b_sv_pageX[4]"  y="&sf.b_sv_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt_now x="&sf.b_sv_pageX[5]"  y="&sf.b_sv_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&sf.b_sv_pageX[6]"  y="&sf.b_sv_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&sf.b_sv_pageX[7]"  y="&sf.b_sv_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&sf.b_sv_pageX[8]"  y="&sf.b_sv_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&sf.b_sv_pageX[9]"  y="&sf.b_sv_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&sf.b_sv_pageX[10]" y="&sf.b_sv_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 6  && sf.SR_page_max >= 6"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è06]
		[pagebt     x="&sf.b_sv_pageX[1]"  y="&sf.b_sv_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&sf.b_sv_pageX[2]"  y="&sf.b_sv_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&sf.b_sv_pageX[3]"  y="&sf.b_sv_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&sf.b_sv_pageX[4]"  y="&sf.b_sv_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&sf.b_sv_pageX[5]"  y="&sf.b_sv_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt_now x="&sf.b_sv_pageX[6]"  y="&sf.b_sv_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&sf.b_sv_pageX[7]"  y="&sf.b_sv_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&sf.b_sv_pageX[8]"  y="&sf.b_sv_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&sf.b_sv_pageX[9]"  y="&sf.b_sv_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&sf.b_sv_pageX[10]" y="&sf.b_sv_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 7  && sf.SR_page_max >= 7"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è07]
		[pagebt     x="&sf.b_sv_pageX[1]"  y="&sf.b_sv_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&sf.b_sv_pageX[2]"  y="&sf.b_sv_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&sf.b_sv_pageX[3]"  y="&sf.b_sv_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&sf.b_sv_pageX[4]"  y="&sf.b_sv_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&sf.b_sv_pageX[5]"  y="&sf.b_sv_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&sf.b_sv_pageX[6]"  y="&sf.b_sv_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt_now x="&sf.b_sv_pageX[7]"  y="&sf.b_sv_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&sf.b_sv_pageX[8]"  y="&sf.b_sv_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&sf.b_sv_pageX[9]"  y="&sf.b_sv_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&sf.b_sv_pageX[10]" y="&sf.b_sv_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 8  && sf.SR_page_max >= 8"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è08]
		[pagebt     x="&sf.b_sv_pageX[1]"  y="&sf.b_sv_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&sf.b_sv_pageX[2]"  y="&sf.b_sv_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&sf.b_sv_pageX[3]"  y="&sf.b_sv_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&sf.b_sv_pageX[4]"  y="&sf.b_sv_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&sf.b_sv_pageX[5]"  y="&sf.b_sv_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&sf.b_sv_pageX[6]"  y="&sf.b_sv_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&sf.b_sv_pageX[7]"  y="&sf.b_sv_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt_now x="&sf.b_sv_pageX[8]"  y="&sf.b_sv_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&sf.b_sv_pageX[9]"  y="&sf.b_sv_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&sf.b_sv_pageX[10]" y="&sf.b_sv_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 9  && sf.SR_page_max >= 9"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è09]
		[pagebt     x="&sf.b_sv_pageX[1]"  y="&sf.b_sv_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&sf.b_sv_pageX[2]"  y="&sf.b_sv_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&sf.b_sv_pageX[3]"  y="&sf.b_sv_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&sf.b_sv_pageX[4]"  y="&sf.b_sv_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&sf.b_sv_pageX[5]"  y="&sf.b_sv_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&sf.b_sv_pageX[6]"  y="&sf.b_sv_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&sf.b_sv_pageX[7]"  y="&sf.b_sv_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&sf.b_sv_pageX[8]"  y="&sf.b_sv_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt_now x="&sf.b_sv_pageX[9]"  y="&sf.b_sv_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt     x="&sf.b_sv_pageX[10]" y="&sf.b_sv_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[elsif exp="sf.SR_page == 10 && sf.SR_page_max >= 10"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_sceneV_init.ks" target=*SR‚ÆƒTƒ€ƒlİ’è10]
		[pagebt     x="&sf.b_sv_pageX[1]"  y="&sf.b_sv_pageY[1]"  graphic="b_page01" target=*SRÄ•`‰æ exp="sf.SR_page = 1"  cond="sf.SR_page_max >= 1"]
		[pagebt     x="&sf.b_sv_pageX[2]"  y="&sf.b_sv_pageY[2]"  graphic="b_page02" target=*SRÄ•`‰æ exp="sf.SR_page = 2"  cond="sf.SR_page_max >= 2"]
		[pagebt     x="&sf.b_sv_pageX[3]"  y="&sf.b_sv_pageY[3]"  graphic="b_page03" target=*SRÄ•`‰æ exp="sf.SR_page = 3"  cond="sf.SR_page_max >= 3"]
		[pagebt     x="&sf.b_sv_pageX[4]"  y="&sf.b_sv_pageY[4]"  graphic="b_page04" target=*SRÄ•`‰æ exp="sf.SR_page = 4"  cond="sf.SR_page_max >= 4"]
		[pagebt     x="&sf.b_sv_pageX[5]"  y="&sf.b_sv_pageY[5]"  graphic="b_page05" target=*SRÄ•`‰æ exp="sf.SR_page = 5"  cond="sf.SR_page_max >= 5"]
		[pagebt     x="&sf.b_sv_pageX[6]"  y="&sf.b_sv_pageY[6]"  graphic="b_page06" target=*SRÄ•`‰æ exp="sf.SR_page = 6"  cond="sf.SR_page_max >= 6"]
		[pagebt     x="&sf.b_sv_pageX[7]"  y="&sf.b_sv_pageY[7]"  graphic="b_page07" target=*SRÄ•`‰æ exp="sf.SR_page = 7"  cond="sf.SR_page_max >= 7"]
		[pagebt     x="&sf.b_sv_pageX[8]"  y="&sf.b_sv_pageY[8]"  graphic="b_page08" target=*SRÄ•`‰æ exp="sf.SR_page = 8"  cond="sf.SR_page_max >= 8"]
		[pagebt     x="&sf.b_sv_pageX[9]"  y="&sf.b_sv_pageY[9]"  graphic="b_page09" target=*SRÄ•`‰æ exp="sf.SR_page = 9"  cond="sf.SR_page_max >= 9"]
		[pagebt_now x="&sf.b_sv_pageX[10]" y="&sf.b_sv_pageY[10]" graphic="b_page10" target=*SRÄ•`‰æ exp="sf.SR_page = 10" cond="sf.SR_page_max >= 10"]
	[endif]

[endmacro]


;---------------------------------------
;          ƒy[ƒWƒ{ƒ^ƒ“ BGM           
;---------------------------------------
[macro name=pagebt_BGM]

	; ƒy[ƒWƒ{ƒ^ƒ“•\¦
	;1ƒy[ƒW‚¾‚¯‚È‚çİ’èƒtƒ@ƒCƒ‹‚¾‚¯“Ç‚İ‚É‚¢‚­
	[if    exp="sf.BGM_page == 1  && sf.BGM_page_max == 1"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è01]
	[elsif exp="sf.BGM_page == 1  && sf.BGM_page_max >= 1"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è01]
		[pagebt_now x="&tf.b_bgm_pageX[1]"  y="&tf.b_bgm_pageY[1]"  graphic="b_page01" target=*BGMÄ•`‰æ exp="sf.BGM_page = 1"  cond="sf.BGM_page_max >= 1"]
		[pagebt     x="&tf.b_bgm_pageX[2]"  y="&tf.b_bgm_pageY[2]"  graphic="b_page02" target=*BGMÄ•`‰æ exp="sf.BGM_page = 2"  cond="sf.BGM_page_max >= 2"]
		[pagebt     x="&tf.b_bgm_pageX[3]"  y="&tf.b_bgm_pageY[3]"  graphic="b_page03" target=*BGMÄ•`‰æ exp="sf.BGM_page = 3"  cond="sf.BGM_page_max >= 3"]
		[pagebt     x="&tf.b_bgm_pageX[4]"  y="&tf.b_bgm_pageY[4]"  graphic="b_page04" target=*BGMÄ•`‰æ exp="sf.BGM_page = 4"  cond="sf.BGM_page_max >= 4"]
		[pagebt     x="&tf.b_bgm_pageX[5]"  y="&tf.b_bgm_pageY[5]"  graphic="b_page05" target=*BGMÄ•`‰æ exp="sf.BGM_page = 5"  cond="sf.BGM_page_max >= 5"]
		[pagebt     x="&tf.b_bgm_pageX[6]"  y="&tf.b_bgm_pageY[6]"  graphic="b_page06" target=*BGMÄ•`‰æ exp="sf.BGM_page = 6"  cond="sf.BGM_page_max >= 6"]
		[pagebt     x="&tf.b_bgm_pageX[7]"  y="&tf.b_bgm_pageY[7]"  graphic="b_page07" target=*BGMÄ•`‰æ exp="sf.BGM_page = 7"  cond="sf.BGM_page_max >= 7"]
		[pagebt     x="&tf.b_bgm_pageX[8]"  y="&tf.b_bgm_pageY[8]"  graphic="b_page08" target=*BGMÄ•`‰æ exp="sf.BGM_page = 8"  cond="sf.BGM_page_max >= 8"]
		[pagebt     x="&tf.b_bgm_pageX[9]"  y="&tf.b_bgm_pageY[9]"  graphic="b_page09" target=*BGMÄ•`‰æ exp="sf.BGM_page = 9"  cond="sf.BGM_page_max >= 9"]
		[pagebt     x="&tf.b_bgm_pageX[10]" y="&tf.b_bgm_pageY[10]" graphic="b_page10" target=*BGMÄ•`‰æ exp="sf.BGM_page = 10" cond="sf.BGM_page_max >= 10"]
	[elsif exp="sf.BGM_page == 2  && sf.BGM_page_max >= 2"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è02]
		[pagebt     x="&tf.b_bgm_pageX[1]"  y="&tf.b_bgm_pageY[1]"  graphic="b_page01" target=*BGMÄ•`‰æ exp="sf.BGM_page = 1"  cond="sf.BGM_page_max >= 1"]
		[pagebt_now x="&tf.b_bgm_pageX[2]"  y="&tf.b_bgm_pageY[2]"  graphic="b_page02" target=*BGMÄ•`‰æ exp="sf.BGM_page = 2"  cond="sf.BGM_page_max >= 2"]
		[pagebt     x="&tf.b_bgm_pageX[3]"  y="&tf.b_bgm_pageY[3]"  graphic="b_page03" target=*BGMÄ•`‰æ exp="sf.BGM_page = 3"  cond="sf.BGM_page_max >= 3"]
		[pagebt     x="&tf.b_bgm_pageX[4]"  y="&tf.b_bgm_pageY[4]"  graphic="b_page04" target=*BGMÄ•`‰æ exp="sf.BGM_page = 4"  cond="sf.BGM_page_max >= 4"]
		[pagebt     x="&tf.b_bgm_pageX[5]"  y="&tf.b_bgm_pageY[5]"  graphic="b_page05" target=*BGMÄ•`‰æ exp="sf.BGM_page = 5"  cond="sf.BGM_page_max >= 5"]
		[pagebt     x="&tf.b_bgm_pageX[6]"  y="&tf.b_bgm_pageY[6]"  graphic="b_page06" target=*BGMÄ•`‰æ exp="sf.BGM_page = 6"  cond="sf.BGM_page_max >= 6"]
		[pagebt     x="&tf.b_bgm_pageX[7]"  y="&tf.b_bgm_pageY[7]"  graphic="b_page07" target=*BGMÄ•`‰æ exp="sf.BGM_page = 7"  cond="sf.BGM_page_max >= 7"]
		[pagebt     x="&tf.b_bgm_pageX[8]"  y="&tf.b_bgm_pageY[8]"  graphic="b_page08" target=*BGMÄ•`‰æ exp="sf.BGM_page = 8"  cond="sf.BGM_page_max >= 8"]
		[pagebt     x="&tf.b_bgm_pageX[9]"  y="&tf.b_bgm_pageY[9]"  graphic="b_page09" target=*BGMÄ•`‰æ exp="sf.BGM_page = 9"  cond="sf.BGM_page_max >= 9"]
		[pagebt     x="&tf.b_bgm_pageX[10]" y="&tf.b_bgm_pageY[10]" graphic="b_page10" target=*BGMÄ•`‰æ exp="sf.BGM_page = 10" cond="sf.BGM_page_max >= 10"]
	[elsif exp="sf.BGM_page == 3  && sf.BGM_page_max >= 3"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è03]
		[pagebt     x="&tf.b_bgm_pageX[1]"  y="&tf.b_bgm_pageY[1]"  graphic="b_page01" target=*BGMÄ•`‰æ exp="sf.BGM_page = 1"  cond="sf.BGM_page_max >= 1"]
		[pagebt     x="&tf.b_bgm_pageX[2]"  y="&tf.b_bgm_pageY[2]"  graphic="b_page02" target=*BGMÄ•`‰æ exp="sf.BGM_page = 2"  cond="sf.BGM_page_max >= 2"]
		[pagebt_now x="&tf.b_bgm_pageX[3]"  y="&tf.b_bgm_pageY[3]"  graphic="b_page03" target=*BGMÄ•`‰æ exp="sf.BGM_page = 3"  cond="sf.BGM_page_max >= 3"]
		[pagebt     x="&tf.b_bgm_pageX[4]"  y="&tf.b_bgm_pageY[4]"  graphic="b_page04" target=*BGMÄ•`‰æ exp="sf.BGM_page = 4"  cond="sf.BGM_page_max >= 4"]
		[pagebt     x="&tf.b_bgm_pageX[5]"  y="&tf.b_bgm_pageY[5]"  graphic="b_page05" target=*BGMÄ•`‰æ exp="sf.BGM_page = 5"  cond="sf.BGM_page_max >= 5"]
		[pagebt     x="&tf.b_bgm_pageX[6]"  y="&tf.b_bgm_pageY[6]"  graphic="b_page06" target=*BGMÄ•`‰æ exp="sf.BGM_page = 6"  cond="sf.BGM_page_max >= 6"]
		[pagebt     x="&tf.b_bgm_pageX[7]"  y="&tf.b_bgm_pageY[7]"  graphic="b_page07" target=*BGMÄ•`‰æ exp="sf.BGM_page = 7"  cond="sf.BGM_page_max >= 7"]
		[pagebt     x="&tf.b_bgm_pageX[8]"  y="&tf.b_bgm_pageY[8]"  graphic="b_page08" target=*BGMÄ•`‰æ exp="sf.BGM_page = 8"  cond="sf.BGM_page_max >= 8"]
		[pagebt     x="&tf.b_bgm_pageX[9]"  y="&tf.b_bgm_pageY[9]"  graphic="b_page09" target=*BGMÄ•`‰æ exp="sf.BGM_page = 9"  cond="sf.BGM_page_max >= 9"]
		[pagebt     x="&tf.b_bgm_pageX[10]" y="&tf.b_bgm_pageY[10]" graphic="b_page10" target=*BGMÄ•`‰æ exp="sf.BGM_page = 10" cond="sf.BGM_page_max >= 10"]
	[elsif exp="sf.BGM_page == 4  && sf.BGM_page_max >= 4"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è04]
		[pagebt     x="&tf.b_bgm_pageX[1]"  y="&tf.b_bgm_pageY[1]"  graphic="b_page01" target=*BGMÄ•`‰æ exp="sf.BGM_page = 1"  cond="sf.BGM_page_max >= 1"]
		[pagebt     x="&tf.b_bgm_pageX[2]"  y="&tf.b_bgm_pageY[2]"  graphic="b_page02" target=*BGMÄ•`‰æ exp="sf.BGM_page = 2"  cond="sf.BGM_page_max >= 2"]
		[pagebt     x="&tf.b_bgm_pageX[3]"  y="&tf.b_bgm_pageY[3]"  graphic="b_page03" target=*BGMÄ•`‰æ exp="sf.BGM_page = 3"  cond="sf.BGM_page_max >= 3"]
		[pagebt_now x="&tf.b_bgm_pageX[4]"  y="&tf.b_bgm_pageY[4]"  graphic="b_page04" target=*BGMÄ•`‰æ exp="sf.BGM_page = 4"  cond="sf.BGM_page_max >= 4"]
		[pagebt     x="&tf.b_bgm_pageX[5]"  y="&tf.b_bgm_pageY[5]"  graphic="b_page05" target=*BGMÄ•`‰æ exp="sf.BGM_page = 5"  cond="sf.BGM_page_max >= 5"]
		[pagebt     x="&tf.b_bgm_pageX[6]"  y="&tf.b_bgm_pageY[6]"  graphic="b_page06" target=*BGMÄ•`‰æ exp="sf.BGM_page = 6"  cond="sf.BGM_page_max >= 6"]
		[pagebt     x="&tf.b_bgm_pageX[7]"  y="&tf.b_bgm_pageY[7]"  graphic="b_page07" target=*BGMÄ•`‰æ exp="sf.BGM_page = 7"  cond="sf.BGM_page_max >= 7"]
		[pagebt     x="&tf.b_bgm_pageX[8]"  y="&tf.b_bgm_pageY[8]"  graphic="b_page08" target=*BGMÄ•`‰æ exp="sf.BGM_page = 8"  cond="sf.BGM_page_max >= 8"]
		[pagebt     x="&tf.b_bgm_pageX[9]"  y="&tf.b_bgm_pageY[9]"  graphic="b_page09" target=*BGMÄ•`‰æ exp="sf.BGM_page = 9"  cond="sf.BGM_page_max >= 9"]
		[pagebt     x="&tf.b_bgm_pageX[10]" y="&tf.b_bgm_pageY[10]" graphic="b_page10" target=*BGMÄ•`‰æ exp="sf.BGM_page = 10" cond="sf.BGM_page_max >= 10"]
	[elsif exp="sf.BGM_page == 5  && sf.BGM_page_max >= 5"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è05]
		[pagebt     x="&tf.b_bgm_pageX[1]"  y="&tf.b_bgm_pageY[1]"  graphic="b_page01" target=*BGMÄ•`‰æ exp="sf.BGM_page = 1"  cond="sf.BGM_page_max >= 1"]
		[pagebt     x="&tf.b_bgm_pageX[2]"  y="&tf.b_bgm_pageY[2]"  graphic="b_page02" target=*BGMÄ•`‰æ exp="sf.BGM_page = 2"  cond="sf.BGM_page_max >= 2"]
		[pagebt     x="&tf.b_bgm_pageX[3]"  y="&tf.b_bgm_pageY[3]"  graphic="b_page03" target=*BGMÄ•`‰æ exp="sf.BGM_page = 3"  cond="sf.BGM_page_max >= 3"]
		[pagebt     x="&tf.b_bgm_pageX[4]"  y="&tf.b_bgm_pageY[4]"  graphic="b_page04" target=*BGMÄ•`‰æ exp="sf.BGM_page = 4"  cond="sf.BGM_page_max >= 4"]
		[pagebt_now x="&tf.b_bgm_pageX[5]"  y="&tf.b_bgm_pageY[5]"  graphic="b_page05" target=*BGMÄ•`‰æ exp="sf.BGM_page = 5"  cond="sf.BGM_page_max >= 5"]
		[pagebt     x="&tf.b_bgm_pageX[6]"  y="&tf.b_bgm_pageY[6]"  graphic="b_page06" target=*BGMÄ•`‰æ exp="sf.BGM_page = 6"  cond="sf.BGM_page_max >= 6"]
		[pagebt     x="&tf.b_bgm_pageX[7]"  y="&tf.b_bgm_pageY[7]"  graphic="b_page07" target=*BGMÄ•`‰æ exp="sf.BGM_page = 7"  cond="sf.BGM_page_max >= 7"]
		[pagebt     x="&tf.b_bgm_pageX[8]"  y="&tf.b_bgm_pageY[8]"  graphic="b_page08" target=*BGMÄ•`‰æ exp="sf.BGM_page = 8"  cond="sf.BGM_page_max >= 8"]
		[pagebt     x="&tf.b_bgm_pageX[9]"  y="&tf.b_bgm_pageY[9]"  graphic="b_page09" target=*BGMÄ•`‰æ exp="sf.BGM_page = 9"  cond="sf.BGM_page_max >= 9"]
		[pagebt     x="&tf.b_bgm_pageX[10]" y="&tf.b_bgm_pageY[10]" graphic="b_page10" target=*BGMÄ•`‰æ exp="sf.BGM_page = 10" cond="sf.BGM_page_max >= 10"]
	[elsif exp="sf.BGM_page == 6  && sf.BGM_page_max >= 6"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è06]
		[pagebt     x="&tf.b_bgm_pageX[1]"  y="&tf.b_bgm_pageY[1]"  graphic="b_page01" target=*BGMÄ•`‰æ exp="sf.BGM_page = 1"  cond="sf.BGM_page_max >= 1"]
		[pagebt     x="&tf.b_bgm_pageX[2]"  y="&tf.b_bgm_pageY[2]"  graphic="b_page02" target=*BGMÄ•`‰æ exp="sf.BGM_page = 2"  cond="sf.BGM_page_max >= 2"]
		[pagebt     x="&tf.b_bgm_pageX[3]"  y="&tf.b_bgm_pageY[3]"  graphic="b_page03" target=*BGMÄ•`‰æ exp="sf.BGM_page = 3"  cond="sf.BGM_page_max >= 3"]
		[pagebt     x="&tf.b_bgm_pageX[4]"  y="&tf.b_bgm_pageY[4]"  graphic="b_page04" target=*BGMÄ•`‰æ exp="sf.BGM_page = 4"  cond="sf.BGM_page_max >= 4"]
		[pagebt     x="&tf.b_bgm_pageX[5]"  y="&tf.b_bgm_pageY[5]"  graphic="b_page05" target=*BGMÄ•`‰æ exp="sf.BGM_page = 5"  cond="sf.BGM_page_max >= 5"]
		[pagebt_now x="&tf.b_bgm_pageX[6]"  y="&tf.b_bgm_pageY[6]"  graphic="b_page06" target=*BGMÄ•`‰æ exp="sf.BGM_page = 6"  cond="sf.BGM_page_max >= 6"]
		[pagebt     x="&tf.b_bgm_pageX[7]"  y="&tf.b_bgm_pageY[7]"  graphic="b_page07" target=*BGMÄ•`‰æ exp="sf.BGM_page = 7"  cond="sf.BGM_page_max >= 7"]
		[pagebt     x="&tf.b_bgm_pageX[8]"  y="&tf.b_bgm_pageY[8]"  graphic="b_page08" target=*BGMÄ•`‰æ exp="sf.BGM_page = 8"  cond="sf.BGM_page_max >= 8"]
		[pagebt     x="&tf.b_bgm_pageX[9]"  y="&tf.b_bgm_pageY[9]"  graphic="b_page09" target=*BGMÄ•`‰æ exp="sf.BGM_page = 9"  cond="sf.BGM_page_max >= 9"]
		[pagebt     x="&tf.b_bgm_pageX[10]" y="&tf.b_bgm_pageY[10]" graphic="b_page10" target=*BGMÄ•`‰æ exp="sf.BGM_page = 10" cond="sf.BGM_page_max >= 10"]
	[elsif exp="sf.BGM_page == 7  && sf.BGM_page_max >= 7"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è07]
		[pagebt     x="&tf.b_bgm_pageX[1]"  y="&tf.b_bgm_pageY[1]"  graphic="b_page01" target=*BGMÄ•`‰æ exp="sf.BGM_page = 1"  cond="sf.BGM_page_max >= 1"]
		[pagebt     x="&tf.b_bgm_pageX[2]"  y="&tf.b_bgm_pageY[2]"  graphic="b_page02" target=*BGMÄ•`‰æ exp="sf.BGM_page = 2"  cond="sf.BGM_page_max >= 2"]
		[pagebt     x="&tf.b_bgm_pageX[3]"  y="&tf.b_bgm_pageY[3]"  graphic="b_page03" target=*BGMÄ•`‰æ exp="sf.BGM_page = 3"  cond="sf.BGM_page_max >= 3"]
		[pagebt     x="&tf.b_bgm_pageX[4]"  y="&tf.b_bgm_pageY[4]"  graphic="b_page04" target=*BGMÄ•`‰æ exp="sf.BGM_page = 4"  cond="sf.BGM_page_max >= 4"]
		[pagebt     x="&tf.b_bgm_pageX[5]"  y="&tf.b_bgm_pageY[5]"  graphic="b_page05" target=*BGMÄ•`‰æ exp="sf.BGM_page = 5"  cond="sf.BGM_page_max >= 5"]
		[pagebt     x="&tf.b_bgm_pageX[6]"  y="&tf.b_bgm_pageY[6]"  graphic="b_page06" target=*BGMÄ•`‰æ exp="sf.BGM_page = 6"  cond="sf.BGM_page_max >= 6"]
		[pagebt_now x="&tf.b_bgm_pageX[7]"  y="&tf.b_bgm_pageY[7]"  graphic="b_page07" target=*BGMÄ•`‰æ exp="sf.BGM_page = 7"  cond="sf.BGM_page_max >= 7"]
		[pagebt     x="&tf.b_bgm_pageX[8]"  y="&tf.b_bgm_pageY[8]"  graphic="b_page08" target=*BGMÄ•`‰æ exp="sf.BGM_page = 8"  cond="sf.BGM_page_max >= 8"]
		[pagebt     x="&tf.b_bgm_pageX[9]"  y="&tf.b_bgm_pageY[9]"  graphic="b_page09" target=*BGMÄ•`‰æ exp="sf.BGM_page = 9"  cond="sf.BGM_page_max >= 9"]
		[pagebt     x="&tf.b_bgm_pageX[10]" y="&tf.b_bgm_pageY[10]" graphic="b_page10" target=*BGMÄ•`‰æ exp="sf.BGM_page = 10" cond="sf.BGM_page_max >= 10"]
	[elsif exp="sf.BGM_page == 8  && sf.BGM_page_max >= 8"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è08]
		[pagebt     x="&tf.b_bgm_pageX[1]"  y="&tf.b_bgm_pageY[1]"  graphic="b_page01" target=*BGMÄ•`‰æ exp="sf.BGM_page = 1"  cond="sf.BGM_page_max >= 1"]
		[pagebt     x="&tf.b_bgm_pageX[2]"  y="&tf.b_bgm_pageY[2]"  graphic="b_page02" target=*BGMÄ•`‰æ exp="sf.BGM_page = 2"  cond="sf.BGM_page_max >= 2"]
		[pagebt     x="&tf.b_bgm_pageX[3]"  y="&tf.b_bgm_pageY[3]"  graphic="b_page03" target=*BGMÄ•`‰æ exp="sf.BGM_page = 3"  cond="sf.BGM_page_max >= 3"]
		[pagebt     x="&tf.b_bgm_pageX[4]"  y="&tf.b_bgm_pageY[4]"  graphic="b_page04" target=*BGMÄ•`‰æ exp="sf.BGM_page = 4"  cond="sf.BGM_page_max >= 4"]
		[pagebt     x="&tf.b_bgm_pageX[5]"  y="&tf.b_bgm_pageY[5]"  graphic="b_page05" target=*BGMÄ•`‰æ exp="sf.BGM_page = 5"  cond="sf.BGM_page_max >= 5"]
		[pagebt     x="&tf.b_bgm_pageX[6]"  y="&tf.b_bgm_pageY[6]"  graphic="b_page06" target=*BGMÄ•`‰æ exp="sf.BGM_page = 6"  cond="sf.BGM_page_max >= 6"]
		[pagebt     x="&tf.b_bgm_pageX[7]"  y="&tf.b_bgm_pageY[7]"  graphic="b_page07" target=*BGMÄ•`‰æ exp="sf.BGM_page = 7"  cond="sf.BGM_page_max >= 7"]
		[pagebt_now x="&tf.b_bgm_pageX[8]"  y="&tf.b_bgm_pageY[8]"  graphic="b_page08" target=*BGMÄ•`‰æ exp="sf.BGM_page = 8"  cond="sf.BGM_page_max >= 8"]
		[pagebt     x="&tf.b_bgm_pageX[9]"  y="&tf.b_bgm_pageY[9]"  graphic="b_page09" target=*BGMÄ•`‰æ exp="sf.BGM_page = 9"  cond="sf.BGM_page_max >= 9"]
		[pagebt     x="&tf.b_bgm_pageX[10]" y="&tf.b_bgm_pageY[10]" graphic="b_page10" target=*BGMÄ•`‰æ exp="sf.BGM_page = 10" cond="sf.BGM_page_max >= 10"]
	[elsif exp="sf.BGM_page == 9  && sf.BGM_page_max >= 9"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è09]
		[pagebt     x="&tf.b_bgm_pageX[1]"  y="&tf.b_bgm_pageY[1]"  graphic="b_page01" target=*BGMÄ•`‰æ exp="sf.BGM_page = 1"  cond="sf.BGM_page_max >= 1"]
		[pagebt     x="&tf.b_bgm_pageX[2]"  y="&tf.b_bgm_pageY[2]"  graphic="b_page02" target=*BGMÄ•`‰æ exp="sf.BGM_page = 2"  cond="sf.BGM_page_max >= 2"]
		[pagebt     x="&tf.b_bgm_pageX[3]"  y="&tf.b_bgm_pageY[3]"  graphic="b_page03" target=*BGMÄ•`‰æ exp="sf.BGM_page = 3"  cond="sf.BGM_page_max >= 3"]
		[pagebt     x="&tf.b_bgm_pageX[4]"  y="&tf.b_bgm_pageY[4]"  graphic="b_page04" target=*BGMÄ•`‰æ exp="sf.BGM_page = 4"  cond="sf.BGM_page_max >= 4"]
		[pagebt     x="&tf.b_bgm_pageX[5]"  y="&tf.b_bgm_pageY[5]"  graphic="b_page05" target=*BGMÄ•`‰æ exp="sf.BGM_page = 5"  cond="sf.BGM_page_max >= 5"]
		[pagebt     x="&tf.b_bgm_pageX[6]"  y="&tf.b_bgm_pageY[6]"  graphic="b_page06" target=*BGMÄ•`‰æ exp="sf.BGM_page = 6"  cond="sf.BGM_page_max >= 6"]
		[pagebt     x="&tf.b_bgm_pageX[7]"  y="&tf.b_bgm_pageY[7]"  graphic="b_page07" target=*BGMÄ•`‰æ exp="sf.BGM_page = 7"  cond="sf.BGM_page_max >= 7"]
		[pagebt     x="&tf.b_bgm_pageX[8]"  y="&tf.b_bgm_pageY[8]"  graphic="b_page08" target=*BGMÄ•`‰æ exp="sf.BGM_page = 8"  cond="sf.BGM_page_max >= 8"]
		[pagebt_now x="&tf.b_bgm_pageX[9]"  y="&tf.b_bgm_pageY[9]"  graphic="b_page09" target=*BGMÄ•`‰æ exp="sf.BGM_page = 9"  cond="sf.BGM_page_max >= 9"]
		[pagebt     x="&tf.b_bgm_pageX[10]" y="&tf.b_bgm_pageY[10]" graphic="b_page10" target=*BGMÄ•`‰æ exp="sf.BGM_page = 10" cond="sf.BGM_page_max >= 10"]
	[elsif exp="sf.BGM_page == 10 && sf.BGM_page_max >= 10"]
		;ƒy[ƒW‚ÌŠe€–Ú‚ÉCG‚ÆƒTƒ€ƒl‚ğİ’èƒTƒuƒ‹[ƒ`ƒ“ŒÄ‚Ño‚µ
		[call storage="b_bgmmode_init.ks" target=*BGM‚Æƒ{ƒ^ƒ“İ’è10]
		[pagebt     x="&tf.b_bgm_pageX[1]"  y="&tf.b_bgm_pageY[1]"  graphic="b_page01" target=*BGMÄ•`‰æ exp="sf.BGM_page = 1"  cond="sf.BGM_page_max >= 1"]
		[pagebt     x="&tf.b_bgm_pageX[2]"  y="&tf.b_bgm_pageY[2]"  graphic="b_page02" target=*BGMÄ•`‰æ exp="sf.BGM_page = 2"  cond="sf.BGM_page_max >= 2"]
		[pagebt     x="&tf.b_bgm_pageX[3]"  y="&tf.b_bgm_pageY[3]"  graphic="b_page03" target=*BGMÄ•`‰æ exp="sf.BGM_page = 3"  cond="sf.BGM_page_max >= 3"]
		[pagebt     x="&tf.b_bgm_pageX[4]"  y="&tf.b_bgm_pageY[4]"  graphic="b_page04" target=*BGMÄ•`‰æ exp="sf.BGM_page = 4"  cond="sf.BGM_page_max >= 4"]
		[pagebt     x="&tf.b_bgm_pageX[5]"  y="&tf.b_bgm_pageY[5]"  graphic="b_page05" target=*BGMÄ•`‰æ exp="sf.BGM_page = 5"  cond="sf.BGM_page_max >= 5"]
		[pagebt     x="&tf.b_bgm_pageX[6]"  y="&tf.b_bgm_pageY[6]"  graphic="b_page06" target=*BGMÄ•`‰æ exp="sf.BGM_page = 6"  cond="sf.BGM_page_max >= 6"]
		[pagebt     x="&tf.b_bgm_pageX[7]"  y="&tf.b_bgm_pageY[7]"  graphic="b_page07" target=*BGMÄ•`‰æ exp="sf.BGM_page = 7"  cond="sf.BGM_page_max >= 7"]
		[pagebt     x="&tf.b_bgm_pageX[8]"  y="&tf.b_bgm_pageY[8]"  graphic="b_page08" target=*BGMÄ•`‰æ exp="sf.BGM_page = 8"  cond="sf.BGM_page_max >= 8"]
		[pagebt     x="&tf.b_bgm_pageX[9]"  y="&tf.b_bgm_pageY[9]"  graphic="b_page09" target=*BGMÄ•`‰æ exp="sf.BGM_page = 9"  cond="sf.BGM_page_max >= 9"]
		[pagebt_now x="&tf.b_bgm_pageX[10]" y="&tf.b_bgm_pageY[10]" graphic="b_page10" target=*BGMÄ•`‰æ exp="sf.BGM_page = 10" cond="sf.BGM_page_max >= 10"]
	[endif]

[endmacro]



[return]
